config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :posts do
    member do
      get "publish"
      get "unpublish"
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :member

    validates_presence_of :title, :body

    def created_signature
        "Created at #{self.created_at.strftime("%Y-%m-%d")} by #{self.member.email}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    layout "blog" #ici qu"on met le layout Administration ou blog selon ce qu'on veut
    def index
        @posts = Post.where(published: true).order(created_at: :DESC).limit(5)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    layout "administration"
    before_action :authenticate_member!

    def index
        @posts = current_member.posts
        respond_to do |format|
          format.html
          format.json { render :json => @posts.to_json }
          format.xml { render :xml => @posts.as_json.to_xml }
        end
    end

    def show
      @post = current_member.posts.find(params[:id])
      respond_to do |format|
        format.html
        format.json { render :json => @post.to_json }
        format.xml { render :xml => @post.as_json.to_xml }
      end
    end

    def new
        @post = Post.new
    end

    def publish
      @post = current_member.posts.find(params[:id])
      @post.update(published: true)
      redirect_to posts_path
    end

    def unpublish
      @post = current_member.posts.find(params[:id])
      @post.update(published: false)
      redirect_to posts_path
    end

    def edit
        @post = current_member.posts.find(params[:id])
    end

    def create
        # Securite lors d'une assignation de masse, on filtre les paramètres authoriser avant de les envoyer au modèle qui gère la base de données
        # Voir fonction privé de ce controlleur
        #post_params = params.require(:post).permit(:title, :body)
        

        @post = current_member.posts.new(post_params)
        
        respond_to do |format|    
          if @post.save # Si la sauvegarde se passe bien, on redirige vers l'action index_5 pour rafraichir le formulaire
            format.html {redirect_to '/posts'}
          else
            format.html {render 'new' } # Si une erreur arrive, on l'affiche sur le formulaire d'origine
          end
          # Si utilisation en javascript
          format.json { render :json => @post.to_json }
          format.xml { render :xml => @post.as_json.to_xml }
        end
    end

    def update
        # Securite lors d'une assignation de masse, on filtre les paramètres authoriser avant de les envoyer au modèle qui gère la base de données
        # Voir fonction privé de ce controlleur
        #post_params = params.require(:post).permit(:title, :body)

        @post = current_member.posts.find(params[:id])        
        
        respond_to do |format|    
          if @post.update(post_params) # Si la sauvegarde se passe bien, on redirige vers l'action index_5 pour rafraichir le formulaire
            format.html {redirect_to '/posts'}
          else
            format.html {render 'edit' } # Si une erreur arrive, on l'affiche sur le formulaire d'origine
          end
          # Si utilisation en javascript
          format.json { render :json => @post.to_json }
          format.xml { render :xml => @post.as_json.to_xml }
        end
    end

    private
    def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<!-- Blog entries -->
<% @posts.each do |post| %>
  <!-- Blog entry -->
  <div class="w3-card-4 w3-margin w3-white">
  <%= image_tag "woods.jpg", style: "width:100%" %>
    <!--<img src="/woods.jpg" alt="Nature" style="width:100%">-->
    <div class="w3-container">
      <h3><b>TITLE HEADING</b></h3>
      <h5><%= post.title %><span class="w3-opacity">April 7, 2014</span></h5>
    </div>

    <div class="w3-container">
      <p><%= post.title %></p>
      <div class="w3-row">
        <div class="w3-col m8 s12">
          <p><button class="w3-button w3-padding-large w3-white w3-border"><b>READ MORE »</b></button></p>
        </div>
        <div class="w3-col m4 w3-hide-small">
          <p><span class="w3-padding-large w3-right"><b>Comments  </b> <span class="w3-tag">0</span></span></p>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <% end %>
<!-- END BLOG ENTRIES -->

app/views/layouts/_menu.html.erb
<%= link_to 'Accueil', root_path, data: { turbolinks: false } %>
    <% if member_signed_in? %>
      <%= link_to 'Mes posts', posts_path %>
      <%= link_to 'logout', destroy_member_session_path, method: "delete" %>
    <% else %>
      <%= link_to 'login', new_member_session_path %>
    <% end %>
    <hr />
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

app/views/layouts/administration.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ADMIN</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin' %>
  </head>

  <body>
    <%= render "layouts/menu" %>
    Partie administrative

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin' %>
  </head>

  <body>
    <%= render "layouts/menu" %>
    
    <%= yield %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'w3' %>
<!--<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">-->
<%= stylesheet_link_tag 'family=Raleway' %>
<!--<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">-->
<style>
body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>
<body class="w3-light-grey">

<!-- w3-content defines a container for fixed size centered content, 
and is wrapped around the whole page content, except for the footer in this example -->
<div class="w3-content" style="max-width:1400px">

<!-- Header -->
<header class="w3-container w3-center w3-padding-32"> 
  <h1><b>MY BLOG</b></h1>
  <%= render "layouts/menu" %>
  <p>Welcome to the blog of <span class="w3-tag">unknown</span></p>
</header>

<!-- Grid -->
<div class="w3-row">
  <div class="w3-col l8 s12">
    <%= yield %>

</div>

<!-- Introduction menu -->
<div class="w3-col l4">
  <!-- About Card -->
  <div class="w3-card w3-margin w3-margin-top">
  <img src="/w3images/avatar_g.jpg" style="width:100%">
    <div class="w3-container w3-white">
      <h4><b>My Name</b></h4>
      <p>Just me, myself and I, exploring the universe of uknownment. I have a heart of love and a interest of lorem ipsum and mauris neque quam blog. I want to share my world with you.</p>
    </div>
  </div><hr>
  
  <!-- Posts -->
  <div class="w3-card w3-margin">
    <div class="w3-container w3-padding">
      <h4>Popular Posts</h4>
    </div>
    <ul class="w3-ul w3-hoverable w3-white">
      <li class="w3-padding-16">
      <%= image_tag("workshop.jpg", width: '50') %>
        <!--<img src="/w3images/workshop.jpg" alt="Image" class="w3-left w3-margin-right" style="width:50px">-->
        <span class="w3-large">Lorem</span><br>
        <span>Sed mattis nunc</span>
      </li>
      <li class="w3-padding-16">
        <%= image_tag("gondol.jpg", width: '50') %>
        <!--<img src="/w3images/gondol.jpg" alt="Image" class="w3-left w3-margin-right" style="width:50px">-->
        <span class="w3-large">Ipsum</span><br>
        <span>Praes tinci sed</span>
      </li> 
      <li class="w3-padding-16">
        <%= image_tag "skies.jpg", width: '50' %>
        <!--<img src="/w3images/skies.jpg" alt="Image" class="w3-left w3-margin-right" style="width:50px">-->
        <span class="w3-large">Dorum</span><br>
        <span>Ultricies congue</span>
      </li>   
      <li class="w3-padding-16 w3-hide-medium w3-hide-small">
        <img src="/w3images/rock.jpg" alt="Image" class="w3-left w3-margin-right" style="width:50px">
        <span class="w3-large">Mingsum</span><br>
        <span>Lorem ipsum dipsum</span>
      </li>  
    </ul>
  </div>
  <hr> 
 
  <!-- Labels / tags -->
  <div class="w3-card w3-margin">
    <div class="w3-container w3-padding">
      <h4>Tags</h4>
    </div>
    <div class="w3-container w3-white">
    <p><span class="w3-tag w3-black w3-margin-bottom">Travel</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">New York</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">London</span>
      <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">IKEA</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">NORWAY</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">DIY</span>
      <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Ideas</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Baby</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Family</span>
      <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">News</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Clothing</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Shopping</span>
      <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Sports</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Games</span>
    </p>
    </div>
  </div>
  
<!-- END Introduction Menu -->
</div>

<!-- END GRID -->
</div><br>

<!-- END w3-content -->
</div>

<!-- Footer -->
<footer class="w3-container w3-dark-grey w3-padding-32 w3-margin-top">
  <button class="w3-button w3-black w3-disabled w3-padding-large w3-margin-bottom">Previous</button>
  <button class="w3-button w3-black w3-padding-large w3-margin-bottom">Next »</button>
  <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>

</body>
</html>

app/views/posts/edit.html.erb
<%= form_for(@post) do |f| %>
  <%= f.label(:title) %>
  <%= @post.errors[:title].join('<br />') %>
  <br/>
  <%= f.text_field(:title) %>
  <br />
  <%= f.label(:body) %>
  <%= @post.errors[:body].join('<br />') %>
  <br/>
  <%= f.text_area(:body, rows: 20, cols:100) %>
  <br />
  <%= submit_tag("Modifier") %>
<% end %>

app/views/posts/index.html.erb
<h1>Mes posts (<%= link_to "New", new_post_path %>)</h1>
<br />
<table>
<% @posts.each do |post| %>
    <tr>
        <td><%= raw post.published ? "<b>Published!</b>" : "&nbsp;" %></td>
        <td>
            <%= post.title %>
        </td>
        <td>
            <% if post.published %>
                <%= link_to 'Unpublish', unpublish_post_path(post) %>
            <% else %>
                <%= link_to 'Publish', publish_post_path(post) %>
            <% end %>
            <%= link_to "edit", edit_post_path(post) %>
        </td>
    </tr>
<% end %>
</table>

app/views/posts/new.html.erb
<%= form_for(@post, method: "post") do |f| %>
  <%= f.label(:title) %>
  <%= @post.errors[:title].join('<br />') %>
  <br/>
  <%= f.text_field(:title) %>
  <br />
  <%= f.label(:body) %>
  <%= @post.errors[:body].join('<br />') %>
  <br/>
  <%= f.text_area(:body, rows: 20, cols:100) %>
  <br />
  <%= submit_tag("Ajouter") %>
<% end %>

app/views/posts/show.html.erb
<%= @post.title %><br />

<p>
    <%= @post.body %>
</p>

<%= @post.created_signature %>